name: Build

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    # monthly
    - cron: "0 0 1 * *"

env:
  #bump to clear caches
  ACTION_CACHE_VERSION: 'v2'
  LEIN_VERSION: '2.9.8'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: ${{ env.LEIN_VERSION }}
      - name: Run trojansourcedetector
        uses: haveyoudebuggedit/trojansourcedetector@v1
      - name: Warm deps cache
        run: lein all deps
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: ${{ env.LEIN_VERSION }}
      - name: Run Eastwood
        run: lein eastwood
  test-jvm:
    needs: setup
    strategy:
      matrix:
        java: ['8', '11', '17', '19']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ env.ACTION_CACHE_VERSION }}-${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: ${{ env.LEIN_VERSION }}
      - name: Run JVM tests
        run: lein test-all
  test-bb:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.10.164-SNAPSHOT
          babashka-url: "https://output.circle-artifacts.com/output/job/e752ca69-381f-4087-83c1-0686444fdf82/artifacts/0/release/babashka-0.10.164-SNAPSHOT-linux-amd64.tar.gz"
      - name: Run Babashka tests
        run: ./bin/bb-test-runner.sh
